version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: kitchensink-backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${POSTGRES_URL:-jdbc:postgresql://postgres:5432/kitchensink}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/kitchensink}
      - SPRING_DATA_MONGODB_DATABASE=${MONGODB_DATABASE:-kitchensink}
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=false
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_FLYWAY_VALIDATE_ON_MIGRATE=true
      - SPRING_FLYWAY_MONGODB_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration/postgresql
      - SPRING_FLYWAY_MONGODB_LOCATIONS=classpath:db/migration/mongodb
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kitchensink-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./frontend/webapp:/usr/share/nginx/html
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://backend:8080}
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend-new:
    build:
      context: ./frontend_react
      dockerfile: Dockerfile
    container_name: kitchensink-frontend-react
    ports:
      - "3001:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://backend:8080}
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend-performance-tests:
    build: 
      context: ./shared/performance-tests
      dockerfile: Dockerfile
    container_name: frontend-performance-tests
    profiles:
      - performance
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    volumes:
      - ./performance-reports:/app/performance-reports:rw
      - ./shared/performance-tests:/app:rw
    environment:
      - NODE_ENV=test
      - DOCKER_BUILD_ID=${DOCKER_BUILD_ID:-latest}
      - TIMESTAMP=${TEST_RUN_TIMESTAMP}
      - VITE_API_URL=http://backend:8080
      - TEST_URL=http://frontend:80
      - APP_PAGE_URL=http://frontend:80
    networks:
      - app-network
    command: sh /app/docker-performance-test.sh "frontend" "http://frontend:80"

  frontend-react-performance-tests:
    build: 
      context: ./shared/performance-tests
      dockerfile: Dockerfile
    container_name: frontend-react-performance-tests
    profiles:
      - performance
    depends_on:
      frontend-new:
        condition: service_healthy
      backend:
        condition: service_healthy
    volumes:
      - ./performance-reports:/app/performance-reports:rw
      - ./shared/performance-tests:/app:rw
    environment:
      - NODE_ENV=test
      - DOCKER_BUILD_ID=${DOCKER_BUILD_ID:-latest}
      - TIMESTAMP=${TEST_RUN_TIMESTAMP}
      - VITE_API_URL=http://backend:8080
      - TEST_URL=http://frontend-new:80
      - APP_PAGE_URL=http://frontend-new:80
    networks:
      - app-network
    command: sh /app/docker-performance-test.sh "frontend-react" "http://frontend-new:80"

  backend-performance-tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: backend-performance-tests
    profiles:
      - performance
    volumes:
      - ./performance-reports:/app/performance-reports:rw
      - ./backend/target:/app/target:rw
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - MONGODB_URI=mongodb://mongodb:27017/kitchensink
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/kitchensink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - TIMESTAMP=${TEST_RUN_TIMESTAMP}
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongodb:/data/db:rw
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=kitchensink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    name: kitchensink_mongodb_data
  postgres_data:
    name: kitchensink_postgres_data 