# src/main/resources/application.yml
spring:
  application:
    name: kitchensink-backend

  datasource:
    url: jdbc:h2:mem:kitchensink
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mongo.kitchensink: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    org.springframework.boot.autoconfigure: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha